version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
